[[social]]
  name = "GitHub"
  url = "https://github.com/SparkyStudios/AmplitudeAudioSDK"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/na2axl/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/na2axl"
  weight = 30
