# Meta Data for SEO

## Homepage
title = "Amplitude Audio SDK"
titleSeparator = "-"
titleAddition = "A powerful and cross-platform audio engine, optimized for games"
description = "Amplitude is a full-featured and cross-platform audio engine designed with the needs of games in mind. With his efficient audio mixer, you have all the controls to play spatialized sounds in 3D environments with custom attenuation models and a lot more."

## Documentation
docsVersion = "1.0"

## Open Graph
images = ["images/logo.png"]
ogLocale = "en_US"
domainTLD = "sparkystudios.github.io"
titleHome = "Amplitude Audio SDK"

## Twitter Cards
twitterSite = "@na2axl"
twitterCreator = "@na2axl"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Amplitude Audio"
schemaAuthor = "Axel Nana"
schemaAuthorTwitter = "https://twitter.com/na2axl"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/na2axl/"
schemaAuthorGitHub = "https://github.com/na2axl"
schemaLocale = "en-US"
schemaLogo = "logo-amplitude.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/na2axl"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/SparkyStudios/AmplitudeAudioSDK"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#74d0f1"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Amplitude Audio SDK - Copyright © 2023 Sparky Studios - Documentation powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>."

# Feed
copyRight = "Copyright © 2023 Sparky Studios"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/SparkyStudios/AmplitudeAudioSDK"
docsRepoBranch = "develop"
docsRepoSubPath = "docs"
editPage = true
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = true
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
