# Blog page section
mainSections = ["posts"]

# Ensure that no sidebar is added to the home page
uniqueHomePage = true

# Link to the project repository
repo = "https://github.com/SparkyStudios/AmplitudeAudioSDK"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = true # Dark mode enabled by default

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 8

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# Site logo
[logo]
  lightMode = "images/logo.svg"
  darkMode = "images/logo.svg"

# Github link
[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/SparkyStudios/AmplitudeAudioSDK"

# Copyright
[author]
  name = "Sparky Studios"
  url = "https://github.com/SparkyStudios/"
