baseURL = "https://sparkystudios.github.io/AmplitudeAudioSDK/"

title = "Amplitude Audio SDK"

enableRobotsTXT = true
publishdir = "../docs/"

theme = ["github.com/onweru/compose"]
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]

[params]
  metaThemeColor = "#74D0F1"
  customJs = ["https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"]
  customCss = ["https://fonts.cdnfonts.com/css/open-sans"]