name: Build

on:
  push:
  pull_request:
  release:
    types:
      - created

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH=${{ github.ref }}

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [cleanup]
    uses: ./.github/workflows/xmake.yml
    with:
      project-path: .
      project-slug: sdk
    name: Amplitude Audio SDK
    secrets: inherit

  release:
    needs: [build]
    runs-on: ${{ matrix.config.os }}
    name: "[${{ matrix.build_type }}] ${{ matrix.config.name }}"
    strategy:
      fail-fast: false
      matrix:
        build_type: ["release", "debug"]
        config:
          - name: "Windows Latest MSVC"
            os: windows-latest
            archiver: "7z a"
            arch: x64
            plat: windows

          - name: "Ubuntu Latest GCC"
            os: ubuntu-24.04
            archiver: "7z a"
            arch: x86_64
            plat: linux

          - name: "Ubuntu Latest Clang"
            os: ubuntu-24.04
            archiver: "7z a"
            arch: x86_64
            plat: linux
            toolchain: clang

          - name: "macOS x64 Latest Clang"
            os: macos-15-intel
            archiver: "7za a"
            arch: x86_64
            plat: macosx

          - name: "macOS arm64 Latest Clang"
            os: macos-15
            archiver: "7za a"
            arch: arm64
            plat: macosx

          - name: "Android x64 Latest Clang"
            os: ubuntu-latest
            archiver: "7za a"
            arch: x86_64
            plat: android

          - name: "Android arm64 Latest Clang"
            os: ubuntu-latest
            archiver: "7za a"
            arch: arm64-v8a
            plat: android

          - name: "Android x86 Latest Clang"
            os: ubuntu-latest
            archiver: "7za a"
            arch: x86
            plat: android

          - name: "Android arm Latest Clang"
            os: ubuntu-latest
            archiver: "7za a"
            arch: armeabi-v7a
            plat: android

          - name: "iOS arm64 Latest Clang"
            os: macos-15
            archiver: "7za a"
            arch: arm64
            plat: iphoneos

          - name: "iOS x86_64 Latest Clang"
            os: macos-15-intel
            archiver: "7za a"
            arch: x86_64
            plat: iphoneos

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Download SDK Artifact
        uses: actions/download-artifact@v4
        with:
          name: sdk-${{ matrix.build_type }}-${{ matrix.config.arch }}-${{ matrix.config.plat }}${{ matrix.config.toolchain && format('-{0}', matrix.config.toolchain) || '' }}
          path: sdk

      - name: Pack
        shell: bash
        run: ${{ matrix.config.archiver }} ./${{ matrix.build_type }}_sdk_${{ matrix.config.arch }}-${{ matrix.config.plat }}.7z LICENSE NOTICE README.md sdk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            LICENSE
            NOTICE
            README.md
            sdk/
          name: ${{ matrix.build_type }}_sdk_${{ matrix.config.arch }}-${{ matrix.config.plat }}${{ matrix.config.toolchain && format('-{0}', matrix.config.toolchain) || '' }}

      - name: Upload release asset
        if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'created')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.build_type }}_sdk_${{ matrix.config.arch }}-${{ matrix.config.plat }}.7z
          asset_name: ${{ matrix.build_type }}_sdk_${{ matrix.config.arch }}-${{ matrix.config.plat }}.7z
          asset_content_type: application/x-7z-compressed
