name: Build CMake Project

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      project-slug:
        required: true
        type: string
      pull-sdk:
        required: false
        type: boolean
        default: false
      sdk-version:
        required: false
        type: string
        default: nightly
      need-flatc:
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: "[${{ matrix.build_type }}] ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [ "release", "debug" ]
        config:
          - name: "Windows Latest MSVC"
            key: msvc
            os: windows-latest
            cc: "cl"
            cxx: "cl"
            generator: "Visual Studio 17 2022"
            target_triplet: x64-windows

          - name: "Ubuntu Latest GCC"
            key: gcc
            os: ubuntu-24.04
            cc: "gcc"
            cxx: "g++"
            generator: "Ninja"
            target_triplet: x64-linux

          - name: "macOS x64 Latest Clang"
            key: clang
            os: macos-13
            cc: "clang"
            cxx: "clang++"
            generator: "Ninja"
            target_triplet: x64-osx

          - name: "macOS arm64 Latest Clang"
            key: clang
            os: macos-14
            cc: "clang"
            cxx: "clang++"
            generator: "Ninja"
            target_triplet: arm64-osx

          - name: "Android x64 Latest Clang"
            os: ubuntu-latest
            cc: "clang"
            cxx: "clang++"
            generator: "Ninja"
            target_triplet: x64-android
            android_abi: x86_64

          - name: "Android arm64 Latest Clang"
            os: ubuntu-latest
            cc: "clang"
            cxx: "clang++"
            generator: "Ninja"
            target_triplet: arm64-android
            android_abi: arm64-v8a

          - name: "Android x86 Latest Clang"
            os: ubuntu-latest
            cc: "clang"
            cxx: "clang++"
            generator: "Ninja"
            target_triplet: x86-android
            android_abi: x86

          - name: "Android arm Latest Clang"
            os: ubuntu-latest
            cc: "clang"
            cxx: "clang++"
            generator: "Ninja"
            target_triplet: arm-neon-android
            android_abi: armeabi-v7a

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Amplitude Audio SDK
        uses: AmplitudeAudio/action-setup-sdk@main
        if: inputs.pull-sdk
        id: sdk_path
        with:
          platforms: |
            ${{ matrix.config.target_triplet }}
          version: ${{ inputs.sdk-version }}
          install-dir: "${{ github.workspace }}/amplitude_audio"
          config: ${{ matrix.build_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: 993c188a0e71002f6b6b959741d57fb8a2edf0ec
          doNotCache: false

      - name: Find flatc version
        if: startsWith(matrix.config.os, 'ubuntu') || startsWith(matrix.config.os, 'macos')
        id: flatc_version
        uses: tdemin/find-latest-tag@v1
        with:
          repo: https://github.com/google/flatbuffers.git

      - name: Install dependencies on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install ninja cmake curl lcov
          [Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";C:\ProgramData\chocolatey\lib\lcov\tools\bin", [EnvironmentVariableTarget]::Machine)
          $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("PATH", "User")
          echo "LCOV_PATH=C:/ProgramData/chocolatey/lib/lcov/tools/bin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          ninja --version
          cmake --version
          lcov --version
          $FLATC_VERSION = "$(curl "https://api.github.com/repos/google/flatbuffers/releases/latest" --ssl-no-revoke --silent | Select-String -Pattern '"tag_name":\s*"(.+)"')" -replace '.*"v(.+)".*','$1'
          echo "flatc download latest v$FLATC_VERSION version"
          iwr -Uri https://github.com/google/flatbuffers/releases/download/v$FLATC_VERSION/Windows.flatc.binary.zip -OutFile flatc.zip
          mkdir bin
          Expand-Archive -Force flatc.zip .\bin\
          .\bin\flatc --version

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install cpanminus autoconf automake libtool pkg-config libltdl-dev ninja-build cmake lcov
          sudo cpanm open
          ninja --version
          cmake --version
          gcc --version
          lcov --version
          wget https://github.com/google/flatbuffers/releases/download/${{ steps.flatc_version.outputs.tag }}/Linux.flatc.binary.g++-13.zip
          mkdir bin
          sudo unzip Linux.flatc.binary.g++-13.zip -d bin
          ./bin/flatc --version

      - name: Setup Android NDK
        id: setup-ndk
        if: startsWith(matrix.config.os, 'ubuntu') && endsWith(matrix.config.target_triplet, 'android')
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Install dependencies on MacOS
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install p7zip cmake ninja lcov
          ninja --version
          cmake --version
          lcov --version
          wget https://github.com/google/flatbuffers/releases/download/${{ steps.flatc_version.outputs.tag }}/Mac.flatc.binary.zip
          mkdir bin
          sudo unzip Mac.flatc.binary.zip -d bin
          ./bin/flatc --version

      - name: Setup Latest Xcode version
        if: startsWith(matrix.config.os, 'macos')
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest

      - name: Restore SDK Cache
        uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          path: sdk
          key: "${{ matrix.build_type }}-${{ inputs.project-slug }}-${{ matrix.config.target_triplet }}-${{ hashFiles('**/sdk') }}"
          restore-keys: |
            ${{ matrix.build_type }}-${{ inputs.project-slug }}-${{ matrix.config.target_triplet }}

      - name: Configure
        if: ${{ !endsWith(matrix.config.target_triplet, 'android') }}
        working-directory: ${{ inputs.project-path }}
        run: |
          mkdir build
          cmake -S . -B build -G "${{ matrix.config.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE:STRING="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET:STRING="${{ matrix.config.target_triplet }}" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DBUILD_SAMPLES:BOOL=TRUE -DBUILD_TOOLS:BOOL=TRUE -DUNIT_TESTS:BOOL=${{ matrix.build_type == 'release' && 'FALSE' || 'TRUE' }}
        env:
          AM_SDK_PATH: "${{ steps.sdk_path.outputs.path }}/sdk"
          AM_SDK_PLATFORM: ${{ matrix.config.target_triplet }}

      - name: Configure
        if: endsWith(matrix.config.target_triplet, 'android')
        working-directory: ${{ inputs.project-path }}
        run: |
          mkdir build
          cmake -S . -B build -G "${{ matrix.config.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE:STRING="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET:STRING="${{ matrix.config.target_triplet }}" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DBUILD_SAMPLES:BOOL=FALSE -DBUILD_TOOLS:BOOL=FALSE -DUNIT_TESTS:BOOL=FALSE -DANDROID_ABI=${{ matrix.config.android_abi }} -DCMAKE_ANDROID_ARCH_ABI=${{ matrix.config.android_abi }} -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} -DCMAKE_ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=21
        env:
          AM_SDK_PATH: "${{ steps.sdk_path.outputs.path }}/sdk"
          AM_SDK_PLATFORM: ${{ matrix.config.target_triplet }}
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Inspect vcpkg errors
        if: failure()
        run: |
          cat ${{ github.workspace }}/build/vcpkg_installed/vcpkg/issue_body.md

      - name: Build
        working-directory: ${{ inputs.project-path }}/build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Test
        if: ${{ matrix.build_type == 'debug' && !endsWith(matrix.config.target_triplet, 'android') }}
        working-directory: ${{ inputs.project-path }}/build/tests
        run: ctest --extra-verbose -C debug
        env:
          AM_SDK_PATH: "${{ steps.sdk_path.outputs.path }}/sdk"
          AM_SDK_PLATFORM: ${{ matrix.config.target_triplet }}

      - name: Generate coverage
        continue-on-error: true
        if: matrix.build_type == 'debug' && !startsWith(matrix.config.os, 'windows')
        working-directory: ${{ inputs.project-path }}/build
        run: |
          lcov --capture --directory . --output-file coverage.info --base-directory . --ignore-errors inconsistent,range,mismatch,source,count,negative
          lcov --remove coverage.info '/usr/*' '${{ github.workspace }}/build/vcpkg_installed/*' '${{ github.workspace }}/src/Utils/*' '${{ github.workspace }}/samples/*' '${{ github.workspace }}/tools/*' --output-file coverage.info  --ignore-errors inconsistent,range,mismatch,source,count,negative

      - name: Upload coverage to Codecov
        continue-on-error: true
        if: matrix.build_type == 'debug' && !startsWith(matrix.config.os, 'windows')
        uses: codecov/codecov-action@v4
        with:
          file: ${{ inputs.project-path }}/build/coverage.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Install Strip
        working-directory: ${{ inputs.project-path }}/build
        run: cmake --install . --strip --config ${{ matrix.build_type }}

      - name: Save SDK Cache
        uses: actions/cache/save@v4
        id: cache
        with:
          enableCrossOsArchive: true
          path: sdk
          key: ${{ matrix.build_type }}-${{ inputs.project-slug }}-${{ matrix.config.target_triplet }}-${{ hashFiles('**/sdk') }}
