name: Build XMake Project

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      project-slug:
        required: true
        type: string
      pull-sdk:
        required: false
        type: boolean
        default: false
      sdk-version:
        required: false
        type: string
        default: nightly
      need-flatc:
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: "[${{ matrix.build_type }}] ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [ "release", "debug", "coverage" ]
        config:
          - name: "Windows Latest MSVC"
            key: msvc
            os: windows-latest
            arch: x64
            plat: windows

          - name: "Ubuntu Latest GCC"
            key: gcc
            os: ubuntu-24.04
            arch: x86_64
            plat: linux

          - name: "macOS x64 Latest Clang"
            key: clang
            os: macos-15-intel
            arch: x86_64
            plat: macosx

          - name: "macOS arm64 Latest Clang"
            key: clang
            os: macos-15
            arch: arm64
            plat: macosx

          - name: "Android x64 Latest Clang"
            os: ubuntu-latest
            arch: x86_64
            plat: android

          - name: "Android arm64 Latest Clang"
            os: ubuntu-latest
            arch: arm64-v8a
            plat: android

          - name: "Android x86 Latest Clang"
            os: ubuntu-latest
            arch: x86
            plat: android

          - name: "Android arm Latest Clang"
            os: ubuntu-latest
            arch: armeabi-v7a
            plat: android
        exclude:
          - build_type: "coverage"
            config:
              plat: android
          - build_type: "coverage"
            config:
              plat: iphoneos

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Amplitude Audio SDK
        uses: AmplitudeAudio/action-setup-sdk@main
        if: inputs.pull-sdk
        id: sdk_path
        with:
          platforms: |
            ${{ matrix.config.arch }}-${{ matrix.config.plat }}
          version: ${{ inputs.sdk-version }}
          install-dir: "${{ github.workspace }}/amplitude_audio"
          config: ${{ matrix.build_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Find flatc version
        if: matrix.config.plat == 'android' || matrix.config.plat == 'iphoneos'
        id: flatc_version
        uses: tdemin/find-latest-tag@v1
        with:
          repo: https://github.com/google/flatbuffers.git

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ${{ matrix.config.arch }}-${{ matrix.config.plat }}

      - name: Install dependencies on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install curl
          xmake --version

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install cpanminus autoconf automake libtool pkg-config libltdl-dev
          sudo cpanm Capture::Tiny DateTime Devel::Cover Digest::MD5 File::Spec JSON::XS Memory::Process Module::Load::Conditional Scalar::Util Time::HiRes TimeDate
          wget https://github.com/linux-test-project/lcov/releases/download/v2.3.2/lcov-2.3.2.tar.gz
          tar -xzf lcov-2.3.2.tar.gz
          cd lcov-2.3.2
          sudo make install
          cd ..
          gcc --version
          lcov --version
          xmake --version

      - name: Setup Android NDK
        id: setup-ndk
        if: matrix.config.plat == 'android'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Install dependencies on MacOS
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install p7zip lcov
          lcov --version
          xmake --version

      - name: Install Local flatc (Android)
        if: matrix.config.plat == 'android'
        run: |
          wget https://github.com/google/flatbuffers/releases/download/${{ steps.flatc_version.outputs.tag }}/Linux.flatc.binary.g++-13.zip
          mkdir bin
          sudo unzip Linux.flatc.binary.g++-13.zip -d bin
          ./bin/flatc --version

      - name: Install Local flatc (iOS)
        if: matrix.config.plat == 'ios'
        run: |
          wget https://github.com/google/flatbuffers/releases/download/${{ steps.flatc_version.outputs.tag }}/Mac.flatc.binary.zip
          mkdir bin
          sudo unzip Mac.flatc.binary.zip -d bin
          ./bin/flatc --version

      - name: Setup Latest Xcode version
        if: startsWith(matrix.config.os, 'macos')
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest

      - name: Restore SDK Cache
        uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          path: sdk
          key: "${{ matrix.build_type }}-${{ inputs.project-slug }}-${{ matrix.config.arch }}-${{ matrix.config.plat }}-${{ hashFiles('**/sdk') }}"
          restore-keys: |
            ${{ matrix.build_type }}-${{ inputs.project-slug }}-${{ matrix.config.arch }}-${{ matrix.config.plat }}

      - name: Configure
        working-directory: ${{ inputs.project-path }}
        run: |
          xmake f -y -a ${{ matrix.config.arch }} -p ${{ matrix.config.plat }} -m ${{ matrix.build_type }} --build_samples=n --build_tools=${{ matrix.config.plat == 'android' && 'n' || 'y' }} --unit_tests=${{ matrix.build_type == 'coverage' && 'y' || 'n' }} --build_assets=${{ matrix.build_type == 'coverage' && 'y' || 'n' }}
        env:
          AM_SDK_PATH: "${{ steps.sdk_path.outputs.path }}/sdk"
          AM_SDK_PLATFORM: "${{ matrix.config.arch }}-${{ matrix.config.plat }}"
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build
        working-directory: ${{ inputs.project-path }}
        run: xmake b -y

      - name: Test
        if: ${{ matrix.build_type == 'coverage' && matrix.config.plat != 'android' }}
        working-directory: ${{ inputs.project-path }}
        run: |
          xmake b -y coverage_generate_baseline_report
          xmake test
        env:
          AM_SDK_PATH: "${{ steps.sdk_path.outputs.path }}/sdk"
          AM_SDK_PLATFORM: "${{ matrix.config.arch }}-${{ matrix.config.plat }}"

      - name: Generate coverage
        continue-on-error: true
        if: matrix.build_type == 'coverage' && !startsWith(matrix.config.os, 'windows')
        working-directory: ${{ inputs.project-path }}
        run: |
          xmake b -y coverage_generate_test_report

      - name: Upload coverage to Codecov
        continue-on-error: true
        if: matrix.build_type == 'coverage' && !startsWith(matrix.config.os, 'windows')
        uses: codecov/codecov-action@v4
        with:
          file: ${{ inputs.project-path }}/build/coverage/data/combined.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Install
        if: matrix.build_type != 'coverage'
        working-directory: ${{ inputs.project-path }}
        run: xmake i -o sdk

      - name: Save SDK Cache
        if: matrix.build_type != 'coverage'
        uses: actions/cache/save@v4
        id: cache
        with:
          enableCrossOsArchive: true
          path: ${{ inputs.project-path }}/sdk
          key: ${{ matrix.build_type }}-${{ inputs.project-slug }}-${{ matrix.config.arch }}-${{ matrix.config.plat }}-${{ hashFiles('**/sdk') }}
